// example/angular/src/app/advanced/map-view.component.ts
import {
  Component,
  ViewChild,
  ElementRef,
  OnInit,
  OnDestroy,
  EventEmitter,
  Output,
  Input,
  NgZone
} from '@angular/core';

import { GoogleMap } from '@capacitor/google-maps';
import { ActionSheet, ActionSheetButtonStyle } from '@capacitor/action-sheet';

import { Haptics, ImpactStyle } from '@capacitor/haptics';

import BackgroundGeolocation, {
	Subscription,
	Geofence,
	Location
} from "@transistorsoft/capacitor-background-geolocation";

import {COLORS} from '../lib/colors';
import {BGService} from "./lib/BGService";

import {
  toRad,
  toDeg,
  getBearing,
  computeOffsetCoordinate
} from "./lib/GeoMath"

/// Polyline points
const POLYLINE_PATH = [];
/// @capacitor/google-maps Marker refs (Circle, Polygon, Marker, Polyline)
const MARKERS = {
  currentLocation: null,
  locationMarkers: [],
  stationaryCircle: null,
  polyline: null,
  activeGeofences: null,
  activePolygons: null,
  geofenceEventMarkers: [],
  geofenceEventPolylines: [],
  addGeofenceCursor: [],
  addGeofencePolygonCursor: null,
  motionChangeCircles: [],
  motionChangePolylines: []
}

/// Active Geofence Map, keyed by Geofence.identifier
const ACTIVE_GEOFENCES = new Map<string, Geofence>();

let POLYGON_GEOFENCE_VERTICES = [];

@Component({
	selector: 'map-view',
  template: `
  	<div id="MapView-container">	 
  		<ion-toolbar [hidden]="!isCreatingPolygon" mode="ios" color="secondary" className="polygon-geofence-menu">
        <ion-title color="light" size="small">Click map to add points</ion-title>
        <ion-buttons slot="start">
          <ion-button (click)="onClickCancelPolygon()" color="danger">Cancel</ion-button>
          <ion-button (click)="onClickUndoPolygon()" color="primary"><ion-icon name="arrow-undo-outline"/></ion-button>
        </ion-buttons>
        <ion-buttons slot="end">
          <ion-button (click)="onClickAddPolygon()" color="primary">Continue</ion-button>
        </ion-buttons>                        
      </ion-toolbar>
      <div id="geofence-prompt" [hidden]="isCreatingPolygon">Click map to add a Geofence</div>
    	<capacitor-google-map id="map"></capacitor-google-map>
    </div>
  `,
  styles: [
  	`  		
      capacitor-google-map {
        display: inline-block;
        height: 1px;
        width: 1px;
      }
      #geofence-prompt {
      	color: #000; 	
      	
        background-color: #fff1a5;
        color: #000000;
        border-bottom-width: 1;
        border-bottom-color: #ccc;

      	font-size: 16px;
      	text-align: center;        
      }
      ion-toolbar {
        background-color: var(--ion-color-secondary);
      }      
      ion-toolbar ion-title {
        color: #000;
      }
    `
  ]
})

export class MapView implements OnInit, OnDestroy {  
  // Fired to container component (eg: AdvancedPage) to inform map is ready.
  @Output() onReady: EventEmitter<any> = new EventEmitter();
  // Fired to container component when the user has selected a coord/vertices on map.
  @Output() onAddGeofence: EventEmitter<any> = new EventEmitter<any>();
  // I hate Ionic and Angular
  @Input() zone: NgZone;
  // BGGeo event subscriptions.
  subscriptions: Array<Subscription>;
  // GoogleMap instance from @capacitor/google-maps 
  map: GoogleMap;
  // Ref to stationaryLocation provided by onMotionChange
  stationaryLocation:Location;
  // Flag when user is creating a polygon on map.
  isCreatingPolygon:boolean;
  // from BackgroundGeolocation.getState().enabled.
  enabled: boolean;

  constructor(private bgService: BGService) {
  	this.subscriptions = [];
  	this.enabled = false;
  	this.isCreatingPolygon = false;
    this.stationaryLocation = null;
  }

	ngOnInit() {
		this.configureBackgroundGeolocation();
		this.createMap();
	}
	  
	ngOnDestroy() {
    this.unsubscribe();
    this.map.destroy()
  }

  subscribe(subscription:Subscription) {
    this.subscriptions.push(subscription);
  }

  unsubscribe() {
    this.subscriptions.forEach((subscription) => subscription.remove() );
    this.subscriptions = [];
  }

  /// Setup BackgroundGeolocation event-listeners.
  async configureBackgroundGeolocation() {  
		const state = await BackgroundGeolocation.getState();
		this.enabled = state.enabled;

		BackgroundGeolocation.onEnabledChange(this.onEnabledChange.bind(this));
		BackgroundGeolocation.onLocation(this.onLocation.bind(this));
		BackgroundGeolocation.onMotionChange(this.onMotionChange.bind(this));
		BackgroundGeolocation.onGeofence(this.onGeofence.bind(this));
		BackgroundGeolocation.onGeofencesChange(this.onGeofencesChange.bind(this));		
  }

  /// Create the map using ion-content element.
  async createMap() {
  	// Ref to @Output callback.
  	const onReady = this.onReady;

  	const ionContent:HTMLElement = document.querySelector('app-advanced ion-content'); 
    const geofencePrompt:HTMLElement = document.querySelector('#geofence-prompt');

    if (ionContent != null) {      
      const mapEl:HTMLElement = document.querySelector('capacitor-google-map'); 

      console.log('- createmap', this.map);

    	this.map = await GoogleMap.create({
	      id: 'google-map',
	      element: mapEl,	// <-- render map onto <ion-content/> element for auto full-screen.
	      apiKey: 'AIzaSyDXTDr2C3iU9jgwpNVpZjeWzOc-DyCgkt8',//environment.apiKey,
	      config: {
	        center: {
	          lat: 45.508888,
	          lng: -73.561668
	        },
	        zoom: 11,
	      }
			});              
      mapEl.style.height = (ionContent.clientHeight - geofencePrompt.clientHeight) + 'px';
      mapEl.style.width = ionContent.clientWidth + 'px';
      
			// listen to mapclicks.  Shame this piece of junk GoogleMap doesn't include a long-press listener...
			this.map.setOnMapClickListener(this.onMapClick.bind(this));  
			// Let the outside world know that the map is ready to rock.
			onReady.emit();
    }        
  }

  /// @event 
  onEnabledChange(enabled) {
    this.enabled = enabled;
  	if (!enabled) {
  		this.clearMarkers();
  	}
  }

  /// @event
  async onLocation(location) {
  	await this.updateCurrentLocationMarker(location);    
  }
  /// @event
  async onMotionChange(event) {
  	if (event.isMoving) {
      if (!this.stationaryLocation) this.stationaryLocation = event.location;
      MARKERS.motionChangeCircles = MARKERS.motionChangeCircles.concat(await this.map.addCircles([this.buildMotionChangeCircle(this.stationaryLocation)]));
      MARKERS.motionChangePolylines = MARKERS.motionChangePolylines.concat(await this.map.addPolylines([this.buildMotionChangePolyline(this.stationaryLocation, event.location)]));
      this.hideStationaryCircle();
    } else {
      this.stationaryLocation = event.location;
      this.showStationaryCircle(event.location);
    }
    this.map.setCamera({      
      zoom: 16
    });    
  }
  /// @event
  async onGeofence(event) {
    const geofence = await BackgroundGeolocation.getGeofence(event.identifier);
    const location = event.location;
    const center = {
      latitude: geofence.latitude,
      longitude: geofence.longitude
    };
    const radius = geofence.radius;

    POLYLINE_PATH.push({
      lat: location.coords.latitude,
      lng: location.coords.longitude
    });        
    

    let color, iconColor;
    if (event.action === 'ENTER') {
      color = COLORS.green;
      iconColor = 'green';
    } else if (event.action === 'DWELL') {
      color = COLORS.gold;
      iconColor = 'amber';
    } else {
      color = COLORS.red
      iconColor = 'red';
    }

    let iconIndex = (location.coords.heading >= 0) ? Math.round(location.coords.heading / 10) : 0;
    if (iconIndex > 36) iconIndex = 0;

    MARKERS.geofenceEventMarkers.push(await this.map.addMarker({
      zIndex: 100,
      coordinate: {
        lat: location.coords.latitude,
        lng: location.coords.longitude
      },
      iconUrl: `assets/imgs/markers/location-arrow-${iconColor}-${iconIndex}.png`,
      iconSize: {
        width: 20,
        height: 20
      },
      iconAnchor: {
        x: 10,
        y: 10
      }      
    }));
    
    const bearing = getBearing(center, location.coords);
    const edgeCoordinate = computeOffsetCoordinate(center, radius, bearing);

    MARKERS.geofenceEventMarkers.push(await this.map.addMarker({
      zIndex: 500,
      coordinate: {
        lat: edgeCoordinate.latitude,
        lng: edgeCoordinate.longitude
      },
      isFlat: true,
      iconUrl: `assets/imgs/markers/geofence-event-edge-circle-${event.action.toLowerCase()}.png`,
      iconSize: {
        width: 10,
        height: 10
      },
      iconAnchor: {
        x: 5,
        y: 5
      }
    }));
    MARKERS.geofenceEventPolylines = MARKERS.geofenceEventPolylines.concat(await this.map.addPolylines([{
      geodesic: true,
      zIndex: 99,
      strokeColor: COLORS.black,
      strokeOpacity: 1.0,
      strokeWeight: 2,
      path: [{
        lat: location.coords.latitude,
        lng: location.coords.longitude
      }, {
        lat: edgeCoordinate.latitude,
        lng: edgeCoordinate.longitude
      }]
    }]));        
  }
  /// @event
  async onGeofencesChange(event) {
  	if (MARKERS.activeGeofences) {      
      await this.map.removeCircles(MARKERS.activeGeofences);
    }
    if (MARKERS.activePolygons) {
      await this.map.removePolygons(MARKERS.activePolygons);
    }
    if ((event.on.length === 0) && (event.off.length === 0)) {
      MARKERS.activeGeofences = null;
      MARKERS.activePolygons = null;
      return;
    }
    event.off.forEach((identifier) => {
      delete ACTIVE_GEOFENCES[identifier];
    });

    event.on.forEach((geofence) => {      
      ACTIVE_GEOFENCES[geofence.identifier] = geofence;
    });

    const circles = [];
    const polygons = [];
    for (const [identifier, geofence] of Object.entries(ACTIVE_GEOFENCES)) {
      circles.push(this.buildGeofenceCircle(geofence));
      if (geofence.vertices.length > 0) {
        polygons.push(this.buildGeofencePolygon(geofence));
      } 
    }
    if (circles.length > 0) {
      this.map.addCircles(circles).then((result) => {
      	MARKERS.activeGeofences = result;
      })
    }
    if (polygons.length > 0) {
      this.map.addPolygons(polygons).then((result) => {
      	MARKERS.activePolygons = result;
      })
    }    
  }

  /// Build red stationary geofence marker.
  async showStationaryCircle(location:Location) {
    await this.hideStationaryCircle();
    
    const state = await BackgroundGeolocation.getState();
    const radius = (state.trackingMode == 1) ? 200 : (state.geofenceProximityRadius! / 2);

    MARKERS.stationaryCircle = await this.map.addCircles([{
      center: {
        lat: location.coords.latitude,
        lng: location.coords.longitude
      },
      fillColor: COLORS.red,
      strokeColor: COLORS.red,
      strokeWeight: 1,
      fillOpacity: 0.3,
      strokeOpacity: 0.7,
      radius: radius
    }]);
  }

  buildMotionChangePolyline(from:Location, to:Location) {
    return {
      zIndex: 8,
      geodesic: true,
      strokeColor: '#00ff00',
      strokeOpacity: 0.7,
      strokeWeight: 10,
      path: [{
        lat: from.coords.latitude,
        lng: from.coords.longitude
      }, {
        lat: to.coords.latitude,
        lng: to.coords.longitude
      }]
    };
  }

  buildMotionChangeCircle(location:Location) {
    return {
      center: {
        lat: location.coords.latitude,
        lng: location.coords.longitude
      },
      fillColor: COLORS.red,
      strokeColor: COLORS.red,
      zIndex: 8,
      fillOpacity: 0.3,
      strokeOpacity: 0.7,
      radius: 25
    };
  }

  /// Hide the red stationary geofence Map Marker.
  async hideStationaryCircle() {
    if (MARKERS.stationaryCircle) {
      this.map.removeCircles(MARKERS.stationaryCircle);
      MARKERS.stationaryCircle = null;
    }    
  }

  /// Build a Geofence Circle Marker
  buildGeofenceCircle(geofence:Geofence) {
    return {
      identifier: geofence.identifier,
      zIndex: 1,
      fillColor: COLORS.green,
      fillOpacity: 0.2,
      strokeColor: COLORS.green,
      strokeWeight: 2,
      strokeOpacity: 0.7,
      params: geofence,
      radius: geofence.radius,
      center: {
        lat: geofence.latitude, 
        lng: geofence.longitude
      }
    };    
  }

  /// Build a Polygon Geofence Marker.
  buildGeofencePolygon(geofence) {
    return {
      zIndex: 2,
      strokeColor: COLORS.blue,
      strokeWeight: 5,
      strokeOpacity: 0.6,
      fillColor: COLORS.polygon_fill_color,
      fillOpacity: 0.4,
      geodesic: true,
      clickable: false,
      title: geofence.identifier,
      paths: geofence.vertices.map((vertex) => {
        return {lat: vertex[0], lng: vertex[1]}
      })
    };
  }

  /// Re-center the map with provided Location.
  async setCenter(location:Location) {    
    if (location.sample) { return; }
              
    this.map.setCamera({
      coordinate: {
        lat: location.coords.latitude,
        lng: location.coords.longitude
      }
    });    
  }

  /// Update current-location Map Marker.
  async updateCurrentLocationMarker(location:Location) {
    return new Promise(async (resolve, reject) => {
      this.setCenter(location);

      if (MARKERS.currentLocation) {
        try {
          await this.map.removeMarker(MARKERS.currentLocation);
        } catch(e) {
          console.warn(e);
        }
        MARKERS.currentLocation = null;
      }
      // Current location "bluedot"
      MARKERS.currentLocation = await this.map.addMarker({
        coordinate: {
          lat: location.coords.latitude,
          lng: location.coords.longitude
        },
        zIndex: 100,
        isFlat: true,
        iconUrl: 'assets/imgs/markers/bluedot.png',
        iconSize: {        
          height: 24,
          width: 24
        },      
        iconAnchor: {
          x: 12,
          y: 12
        }
      });

      // Add a breadcrumb.
      let iconIndex = (location.coords.heading >= 0) ? Math.round(location.coords.heading / 10) : 0;
      if (iconIndex > 36) iconIndex = 0;

      MARKERS.locationMarkers.push(await this.map.addMarker({
        coordinate: {
          lat: location.coords.latitude,
          lng: location.coords.longitude
        },
        isFlat: true,
        zIndex: 10,
        iconUrl: `assets/imgs/markers/location-arrow-${iconIndex}.png`,
        iconSize: {        
          height: 16,
          width: 16
        },
        iconAnchor: {
          x: 8,
          y: 8
        }
      }));

      if (!this.enabled) return;
      
      // Push a new point onto our Polygon path List.    
      POLYLINE_PATH.push({
        lat: location.coords.latitude,
        lng: location.coords.longitude
      });

      // Polyline.
      if (MARKERS.polyline) {
        try {
          this.map.removePolylines(MARKERS.polyline);
        } catch(e) {
          console.warn(e);
        }          
      }
      
      MARKERS.polyline = await this.map.addPolylines([{
        zIndex: 9,
        geodesic: true,
        strokeColor: COLORS.polyline_color,
        strokeOpacity: 0.6,
        strokeWeight: 10,
        path: POLYLINE_PATH
      }]);
      resolve(true);
    })
  }

  /// Clear all Map Markers.
  async clearMarkers() {
    if (!this.map) return;    
    if (MARKERS.stationaryCircle) {
      this.map.removeCircles(MARKERS.stationaryCircle);
      MARKERS.stationaryCircle = null;
    }    
    if (MARKERS.locationMarkers.length > 0) {      
      this.map.removeMarkers(MARKERS.locationMarkers);
      MARKERS.locationMarkers = [];
    }    
    if (MARKERS.polyline) {
      this.map.removePolylines(MARKERS.polyline);
      MARKERS.polyline = null;
      POLYLINE_PATH.splice(0, POLYLINE_PATH.length);
    }
    if (MARKERS.activeGeofences) {
      this.map.removeCircles(MARKERS.activeGeofences);
      MARKERS.activeGeofences = null;
    }
    if (MARKERS.activePolygons) {
      this.map.removePolygons(MARKERS.activePolygons);
      MARKERS.activePolygons = null;
    }
    if (MARKERS.geofenceEventMarkers.length > 0) {
      this.map.removeMarkers(MARKERS.geofenceEventMarkers);
      MARKERS.geofenceEventMarkers = [];
    }    
    if (MARKERS.geofenceEventPolylines.length > 0) {      
      this.map.removePolylines(MARKERS.geofenceEventPolylines);
      MARKERS.geofenceEventPolylines = [];
    }
    if (MARKERS.motionChangePolylines.length > 0) {
      this.map.removePolylines(MARKERS.motionChangePolylines);
      MARKERS.motionChangePolylines = [];
    }
    if (MARKERS.motionChangeCircles.length > 0) {
      this.map.removeCircles(MARKERS.motionChangeCircles);
      MARKERS.motionChangeCircles = [];
    }
  }

  async onMapClick(coords) {    
  	if (this.isCreatingPolygon) {
      this.bgService.playSound('TEST_MODE_CLICK');
      Haptics.impact({ style: ImpactStyle.Heavy });
      POLYGON_GEOFENCE_VERTICES.push([coords.latitude, coords.longitude]); 
      this.renderPolygonGeofenceCursor()
    } else {
      if (MARKERS.addGeofenceCursor.length > 0) {
        this.map.removeMarkers(MARKERS.addGeofenceCursor);
        if (MARKERS.addGeofencePolygonCursor) {
          this.map.removePolygons(MARKERS.addGeofencePolygonCursor);
        }
      }
      // Fire processing off to the containing component (eg: AdvancedApp)
      this.onClickAddGeofence({
        latitude: coords.latitude,
        longitude: coords.longitude
      });
    }
    MARKERS.addGeofenceCursor.push(await this.map.addMarker({      
      coordinate: {
        lat: coords.latitude,
        lng: coords.longitude
      }
    }));
  }

  async onClickAddGeofence(coords) {
    this.bgService.playSound('LONG_PRESS_ACTIVATE');
    Haptics.impact({ style: ImpactStyle.Heavy });

  	const result = await ActionSheet.showActions({
      title: 'Add Geofence',
      message: 'Circular or Polygon',
      options: [
        {
          title: 'Circular',
        },
        {
          title: 'Polygon',
        },
        {
          title: 'Cancel',          
          style: ActionSheetButtonStyle.Destructive,
        },
      ]
    });

    this.isCreatingPolygon = false;
    // Play sound and haptics.
    this.bgService.playSound('TEST_MODE_CLICK');
    Haptics.impact({ style: ImpactStyle.Heavy });

    switch (result.index) {
      case 0:        
        this.onAddGeofence.emit(coords);
        break;
      case 1:
        // polygon
        POLYGON_GEOFENCE_VERTICES.push([coords.latitude, coords.longitude]);
        this.zone.run(() => {
        	this.isCreatingPolygon = true;	
        })        
        break;
      case 2:
        // cancel
      	this.zone.run(() => {
      		this.isCreatingPolygon = false;
      	})
        this.stopCreatingPolygonGeofence();
        break;
    }    
  }

  async stopCreatingPolygonGeofence() {
  	this.zone.run(() => {
  		this.isCreatingPolygon = false;	
  	})
		
    if (MARKERS.addGeofenceCursor.length > 0) {
      this.map.removeMarkers(MARKERS.addGeofenceCursor);
    }
    if (MARKERS.addGeofencePolygonCursor) {
      this.map.removePolygons(MARKERS.addGeofencePolygonCursor);
      MARKERS.addGeofencePolygonCursor = null;
    }      
    POLYGON_GEOFENCE_VERTICES = [];  	
  }

  async renderPolygonGeofenceCursor() {
    // Play sound and haptics.
  	if (MARKERS.addGeofencePolygonCursor) {
      await this.map.removePolygons(MARKERS.addGeofencePolygonCursor);
    }
    if (POLYGON_GEOFENCE_VERTICES.length == 0) {
      return;
    }
    MARKERS.addGeofencePolygonCursor = await this.map.addPolygons([{
      strokeColor: COLORS.blue,
      strokeWeight: 5,
      fillColor: COLORS.polygon_fill_color,
      fillOpacity: 0.4,
      geodesic: true,
      clickable: false,
      paths: POLYGON_GEOFENCE_VERTICES.map((vertex => {
        return {lat: vertex[0], lng: vertex[1]}
      }))
    }])
  }

  /// User clicks [Continue] button to create this Polygon Geofence.
  async onClickAddPolygon() {
    const vertices = POLYGON_GEOFENCE_VERTICES.map((coord) => { return coord; });
    //setGeofenceVertices(vertices);

    // Play sound and haptics.
    this.bgService.playSound('TEST_MODE_CLICK');
    Haptics.impact({ style: ImpactStyle.Heavy });      

    this.zone.run(() => {
    	this.isCreatingPolygon = false;
  	});
    this.onAddGeofence.emit(vertices);

    this.stopCreatingPolygonGeofence();    
  }


  /// User clicks [Cancel] Polygon Geofence.
  async onClickCancelPolygon() {
    this.bgService.playSound('TEST_MODE_CLICK');
    Haptics.impact({ style: ImpactStyle.Heavy });
  	this.stopCreatingPolygonGeofence();    
  }

  /// User clicks [UNDO] button to delete a Polygon vertex
  async onClickUndoPolygon() {
    this.bgService.playSound('TEST_MODE_CLICK');
    Haptics.impact({ style: ImpactStyle.Heavy });

    POLYGON_GEOFENCE_VERTICES.pop();
    const markerId = MARKERS.addGeofenceCursor.pop();
    if (markerId) {
      this.map.removeMarker(markerId);
    }    
    this.renderPolygonGeofenceCursor();    
  }
}

// example/advanced/src/components/MapView.tsx
/// Google Maps view for the Advanced demo.
/// Uses @capacitor/google-maps native overlay with Ionic components for geofence UX.

import { App } from '@capacitor/app';
import React, { useRef } from 'react';
import { Haptics, ImpactStyle } from '@capacitor/haptics';
import { GoogleMap } from '@capacitor/google-maps';
import { IonButton } from '@ionic/react';

import BackgroundGeolocation, {
  State,
  Subscription,
  Location,
  Geofence,
  GeofenceEvent,
  GeofencesChangeEvent,
  MotionChangeEvent,
} from '@transistorsoft/capacitor-background-geolocation';

import TSDialog from '../lib/Dialog';
import { COLORS } from '../config/Colors';
import AddGeofenceTypeSheet, { AddGeofenceType } from './AddGeofenceTypeSheet';
import AddGeofenceSheet from './AddGeofenceSheet';
import { ENV } from '../config/ENV';
import { getBearing, computeOffsetCoordinate } from '../lib/GeoMath';

// Module-level globals (survive React re-renders)
const SUBSCRIPTIONS: Subscription[] = [];
const POLYLINE_PATH: any[] = [];

const MARKERS: any = {
  currentLocation: null,
  locationMarkers: [],
  stationaryCircle: null,
  polyline: null,
  activeGeofences: null,
  activePolygons: null,
  geofenceEventMarkers: [],
  geofenceEventPolylines: [],
  addGeofenceCursor: [],
  addGeofencePolygonCursor: null,
  motionChangeCircles: [],
  motionChangePolylines: [],
};

const EVENT_QUEUE: any = {
  location: [],
  geofence: [],
  geofencesChange: [],
  motionChange: [],
};

const ACTIVE_GEOFENCES = new Map<string, Geofence>();
let IS_CREATING_POLYGON = false;
let POLYGON_GEOFENCE_VERTICES: number[][] = [];

let map: GoogleMap | null = null;
let stationaryLocation: Location | null = null;
let lastClickTime = 0; // debounce guard for double-firing click listener
let updatingCurrentLocation = false; // mutex for bluedot marker updates

const subscribe = (sub: Subscription) => SUBSCRIPTIONS.push(sub);
const unsubscribe = () => {
  SUBSCRIPTIONS.forEach(sub => sub.remove());
  SUBSCRIPTIONS.splice(0, SUBSCRIPTIONS.length);
};

// Component
interface MapViewProps {
  onReady: (ready: boolean) => void;
  hideAddGeofencePrompt?: boolean;
}

const MapView: React.FC<MapViewProps> = (props) => {
  const dialog = TSDialog.getInstance();
  const mapRef = useRef<HTMLElement>(null as any);

  const [enabled, setEnabled] = React.useState(false);
  const [location, setLocation] = React.useState<Location | null>(null);
  const [motionChangeEvent, setMotionChangeEvent] = React.useState<MotionChangeEvent | null>(null);
  const [geofenceEvent, setGeofenceEvent] = React.useState<GeofenceEvent | null>(null);
  const [geofencesChangeEvent, setGeofencesChangeEvent] = React.useState<GeofencesChangeEvent | null>(null);
  const [mapReady, setMapReady] = React.useState(false);
  const [isCreatingPolygon, setIsCreatingPolygon] = React.useState(false);
  const [mapWidth, setMapWidth] = React.useState(window.innerWidth);
  const [mapHeight, setMapHeight] = React.useState(window.innerHeight - 104);

  // New sheet visibility states (mirroring RN)
  const [isAddGeofenceTypeSheetVisible, setIsAddGeofenceTypeSheetVisible] = React.useState(false);
  const [isAddGeofenceSheetVisible, setIsAddGeofenceSheetVisible] = React.useState(false);
  const [pendingGeofenceCoordinate, setPendingGeofenceCoordinate] = React.useState<{ latitude: number; longitude: number } | null>(null);
  const [pendingPolygonVertices, setPendingPolygonVertices] = React.useState<{ latitude: number; longitude: number }[]>([]);
  const [createPolygonGeofenceCoordinates, setCreatePolygonGeofenceCoordinates] = React.useState<any[]>([]);

  // Main effect
  React.useEffect(() => {
    subscribe(BackgroundGeolocation.onLocation(setLocation, err => {
      console.warn('[onLocation] ERROR:', err);
    }));
    subscribe(BackgroundGeolocation.onMotionChange(setMotionChangeEvent));
    subscribe(BackgroundGeolocation.onGeofence(setGeofenceEvent));
    subscribe(BackgroundGeolocation.onGeofencesChange(setGeofencesChangeEvent));
    subscribe(BackgroundGeolocation.onEnabledChange(setEnabled));

    BackgroundGeolocation.getState().then((s: State) => setEnabled(s.enabled));

    App.getState().then((appState) => {
      if (appState.isActive) {
        createMap();
      } else {
        props.onReady(true);
      }
    });

    const appStateListener = App.addListener('appStateChange', ({ isActive }) => {
      if (isActive && map == null) createMap();
    });

    const handleResize = () => {
      setMapWidth(window.innerWidth);
      setMapHeight(window.innerHeight - 104);
    };
    window.addEventListener('resize', handleResize);

    return () => {
      clearMarkers();
      unsubscribe();
      appStateListener.then(l => l.remove());
      window.removeEventListener('resize', handleResize);
    };
  }, []);

  // Effects
  React.useEffect(() => {
    if (!mapReady || !map) return;
    props.onReady(mapReady);
  }, [mapReady]);

  React.useEffect(() => {
    if (location === null) return;
    if (map === null) { EVENT_QUEUE.location.push(location); return; }
    updateCurrentLocationMarker(location);
  }, [location]);

  React.useEffect(() => {
    if (!map) return;
    if (!enabled) clearMarkers();
  }, [enabled]);

  React.useEffect(() => {
    if (!motionChangeEvent) return;
    if (!map) { EVENT_QUEUE.motionChange.push(motionChangeEvent); return; }
    handleMotionChangeEvent(motionChangeEvent);
  }, [motionChangeEvent]);

  React.useEffect(() => {
    IS_CREATING_POLYGON = isCreatingPolygon;
    if (!isCreatingPolygon) {
      if (MARKERS.addGeofenceCursor.length > 0) map?.removeMarkers(MARKERS.addGeofenceCursor);
      if (MARKERS.addGeofencePolygonCursor) {
        map?.removePolygons(MARKERS.addGeofencePolygonCursor);
        MARKERS.addGeofencePolygonCursor = null;
      }
      POLYGON_GEOFENCE_VERTICES = [];
    }
  }, [isCreatingPolygon]);

  React.useEffect(() => {
    if (!geofenceEvent) return;
    if (!map) {
      EVENT_QUEUE.geofence.push(geofenceEvent);
      EVENT_QUEUE.location.push(geofenceEvent.location);
      return;
    }
    handleGeofenceEvent(geofenceEvent);
    updateCurrentLocationMarker(geofenceEvent.location);
  }, [geofenceEvent]);

  React.useEffect(() => {
    if (!geofencesChangeEvent) return;
    if (!map) { EVENT_QUEUE.geofencesChange.push(geofencesChangeEvent); return; }
    updateGeofences(geofencesChangeEvent);
  }, [geofencesChangeEvent]);

  // Map creation
  const createMap = async () => {
    if (!mapRef.current || map) return;

    map = await GoogleMap.create({
      id: 'map',
      element: mapRef.current,
      apiKey: ENV.GOOGLE_MAPS_API_KEY,
      forceCreate: true,
      config: { center: { lat: 45.508888, lng: -73.561668 }, zoom: 16 },
    });

    map.setOnMapClickListener(onMapClick);
    map.setCamera({ zoom: 16 });

    setMapWidth(window.innerWidth);
    setMapHeight(window.innerHeight - 104);
    setMapReady(true);

    // Flush queued events
    if (EVENT_QUEUE.location.length > 0) {
      const lastLoc = EVENT_QUEUE.location[EVENT_QUEUE.location.length - 1];
      await updateCurrentLocationMarker(lastLoc);
    }
    EVENT_QUEUE.location.forEach(async (loc: Location) => {
      MARKERS.locationMarkers.push(await map!.addMarker(buildLocationMarker(loc)));
      POLYLINE_PATH.push({ lat: loc.coords.latitude, lng: loc.coords.longitude });
    });
    if (POLYLINE_PATH.length > 0) {
      MARKERS.polyline = await map.addPolylines([{
        zIndex: 9, geodesic: true,
        strokeColor: COLORS.polyline_color, strokeOpacity: 0.6, strokeWeight: 10,
        path: POLYLINE_PATH,
      }]);
    }
    EVENT_QUEUE.geofence.forEach(async (e: any) => { await handleGeofenceEvent(e); });
    EVENT_QUEUE.motionChange.forEach(async (e: any) => { await handleMotionChangeEvent(e); });
    EVENT_QUEUE.geofencesChange.forEach(async (e: any) => { await updateGeofences(e); });

    if (EVENT_QUEUE.location.length > 0) setCenter(EVENT_QUEUE.location.pop());

    EVENT_QUEUE.location = [];
    EVENT_QUEUE.geofence = [];
    EVENT_QUEUE.motionChange = [];
    EVENT_QUEUE.geofencesChange = [];
  };

  // Map-click listener
  const onMapClick = React.useCallback(async (coords: any) => {
    // Guard against double-fire (StrictMode / duplicate listener registration)
    const now = Date.now();
    if (now - lastClickTime < 300) return;
    lastClickTime = now;

    if (IS_CREATING_POLYGON) {
      dialog.playSound('TEST_MODE_CLICK');
      Haptics.impact({ style: ImpactStyle.Heavy });
      POLYGON_GEOFENCE_VERTICES.push([coords.latitude, coords.longitude]);
      setCreatePolygonGeofenceCoordinates(prev => [
        ...prev,
        { latitude: coords.latitude, longitude: coords.longitude },
      ]);
      renderPolygonGeofenceCursor();
      // Add numbered vertex marker (static PNGs: polygon-vertex-1.png .. polygon-vertex-20.png)
      const vertexIndex = POLYGON_GEOFENCE_VERTICES.length;
      const markerId = await map?.addMarker({
        coordinate: { lat: coords.latitude, lng: coords.longitude },
        iconUrl: `markers/polygon-vertex-${vertexIndex}.png`,
        iconSize: { width: 24, height: 24 },
        iconAnchor: { x: 12, y: 12 },
        isFlat: true,
        zIndex: 200,
      });
      if (markerId !== undefined) MARKERS.addGeofenceCursor.push(markerId);
    } else {
      if (MARKERS.addGeofenceCursor.length > 0) {
        map?.removeMarkers(MARKERS.addGeofenceCursor);
        if (MARKERS.addGeofencePolygonCursor) map?.removePolygons(MARKERS.addGeofencePolygonCursor);
        MARKERS.addGeofenceCursor = [];
      }
      // Show geofence type action sheet — no marker on initial click
      setPendingGeofenceCoordinate({ latitude: coords.latitude, longitude: coords.longitude });
      dialog.playSound('LONG_PRESS_ACTIVATE');
      Haptics.impact({ style: ImpactStyle.Heavy });
      setIsAddGeofenceTypeSheetVisible(true);
    }
  }, []);

  // Geofence type selection handler
  const onSelectAddGeofenceType = React.useCallback((type: AddGeofenceType) => {
    switch (type) {
      case 'circular':
        if (!pendingGeofenceCoordinate) {
          console.log('[MapView] No pendingGeofenceCoordinate yet.');
          setIsAddGeofenceTypeSheetVisible(false);
          return;
        }
        setIsAddGeofenceTypeSheetVisible(false);
        setIsAddGeofenceSheetVisible(true);
        break;
      case 'polygon':
        IS_CREATING_POLYGON = true;
        POLYGON_GEOFENCE_VERTICES = [];
        setCreatePolygonGeofenceCoordinates([]);
        setIsCreatingPolygon(true);
        setIsAddGeofenceTypeSheetVisible(false);
        break;
      case 'cancel':
      default:
        setIsCreatingPolygon(false);
        setCreatePolygonGeofenceCoordinates([]);
        setPendingPolygonVertices([]);
        setIsAddGeofenceTypeSheetVisible(false);
        break;
    }
  }, [pendingGeofenceCoordinate]);

  // Polygon geofence UX
  const renderPolygonGeofenceCursor = async () => {
    if (MARKERS.addGeofencePolygonCursor) await map?.removePolygons(MARKERS.addGeofencePolygonCursor);
    if (POLYGON_GEOFENCE_VERTICES.length === 0) return;
    MARKERS.addGeofencePolygonCursor = await map?.addPolygons([{
      strokeColor: COLORS.blue, strokeWeight: 5, strokeOpacity: 0.6,
      fillColor: COLORS.polygon_fill_color, fillOpacity: 0.4,
      geodesic: true, clickable: false,
      paths: POLYGON_GEOFENCE_VERTICES.map(v => ({ lat: v[0], lng: v[1] })),
    }]);
  };

  const onClickAddPolygon = () => {
    if (createPolygonGeofenceCoordinates.length < 3) {
      console.log('[MapView] polygon next ignored (need >= 3 vertices)');
      return;
    }
    setPendingPolygonVertices(createPolygonGeofenceCoordinates);
    setIsCreatingPolygon(false);
    setIsAddGeofenceSheetVisible(true);
    dialog.playSound('TEST_MODE_CLICK');
    Haptics.impact({ style: ImpactStyle.Heavy });
  };

  const onClickCancelPolygon = () => {
    setIsCreatingPolygon(false);
    setCreatePolygonGeofenceCoordinates([]);
    setPendingGeofenceCoordinate(null);
    dialog.playSound('TEST_MODE_CLICK');
    Haptics.impact({ style: ImpactStyle.Heavy });
  };

  const onClickUndoPolygon = () => {
    POLYGON_GEOFENCE_VERTICES.pop();
    setCreatePolygonGeofenceCoordinates(prev => prev.slice(0, -1));
    const markerId = MARKERS.addGeofenceCursor.pop();
    if (markerId) map?.removeMarker(markerId);
    renderPolygonGeofenceCursor();
    dialog.playSound('TEST_MODE_CLICK');
    Haptics.impact({ style: ImpactStyle.Heavy });
  };

  // Location marker helpers
  const updateCurrentLocationMarker = async (loc: Location) => {
    if (!map) return;
    // Serialize updates to prevent duplicate bluedot markers from async races
    if (updatingCurrentLocation) return;
    updatingCurrentLocation = true;
    try {
      const oldMarker = MARKERS.currentLocation;
      MARKERS.currentLocation = null;
      if (oldMarker) {
        try { await map.removeMarker(oldMarker); } catch (_e) {}
      }
      MARKERS.currentLocation = await map.addMarker({
        coordinate: { lat: loc.coords.latitude, lng: loc.coords.longitude },
        zIndex: 100, isFlat: true,
        iconUrl: 'markers/bluedot.png',
        iconSize: { height: 24, width: 24 },
        iconAnchor: { x: 12, y: 12 },
      });
    } finally {
      updatingCurrentLocation = false;
    }

    MARKERS.locationMarkers.push(await map.addMarker(buildLocationMarker(loc)));

    if (!enabled) return;

    POLYLINE_PATH.push({ lat: loc.coords.latitude, lng: loc.coords.longitude });
    if (MARKERS.polyline) {
      try { map.removePolylines(MARKERS.polyline); } catch (_e) {}
    }
    MARKERS.polyline = await map.addPolylines([{
      zIndex: 9, geodesic: true,
      strokeColor: COLORS.polyline_color, strokeOpacity: 0.6, strokeWeight: 10,
      path: POLYLINE_PATH,
    }]);
    setCenter(loc);
  };

  const buildLocationMarker = (loc: Location) => {
    let iconIndex = (loc.coords.heading >= 0) ? Math.round(loc.coords.heading / 10) : 0;
    if (iconIndex > 36) iconIndex = 0;
    return {
      coordinate: { lat: loc.coords.latitude, lng: loc.coords.longitude },
      isFlat: true, zIndex: 10,
      iconUrl: `markers/location-arrow-${iconIndex}.png`,
      iconSize: { height: 16, width: 16 },
      iconAnchor: { x: 8, y: 8 },
    };
  };

  const setCenter = async (loc: Location) => {
    if (!map || loc.sample) return;
    map.setCamera({ coordinate: { lat: loc.coords.latitude, lng: loc.coords.longitude } });
  };

  // Motion-change helpers
  const handleMotionChangeEvent = async (evt: MotionChangeEvent) => {
    const loc = evt.location;
    if (evt.isMoving) {
      if (!stationaryLocation) stationaryLocation = loc;
      map?.addCircles([buildMotionChangeCircle(stationaryLocation!)]).then(r => {
        MARKERS.motionChangeCircles = MARKERS.motionChangeCircles.concat(r);
      });
      map?.addPolylines([buildMotionChangePolyline(stationaryLocation!, loc)]).then(r => {
        MARKERS.motionChangePolylines = MARKERS.motionChangePolylines.concat(r);
      });
      hideStationaryCircle();
    } else {
      stationaryLocation = loc;
      showStationaryCircle(loc);
    }
    map?.setCamera({ zoom: 16 });
  };

  const buildMotionChangeCircle = (loc: Location) => ({
    center: { lat: loc.coords.latitude, lng: loc.coords.longitude },
    fillColor: COLORS.red, strokeColor: COLORS.red,
    zIndex: 8, fillOpacity: 0.3, strokeOpacity: 0.7, radius: 25,
  });

  const buildMotionChangePolyline = (from: Location, to: Location) => ({
    zIndex: 8, geodesic: true,
    strokeColor: '#00ff00', strokeOpacity: 0.7, strokeWeight: 10,
    path: [
      { lat: from.coords.latitude, lng: from.coords.longitude },
      { lat: to.coords.latitude, lng: to.coords.longitude },
    ],
  });

  const showStationaryCircle = async (loc: Location) => {
    await hideStationaryCircle();
    const s = await BackgroundGeolocation.getState();
    const radius = (s.trackingMode === 1) ? 200 : ((s.geofenceProximityRadius ?? 1000) / 2);
    MARKERS.stationaryCircle = await map?.addCircles([{
      zIndex: 1,
      center: { lat: loc.coords.latitude, lng: loc.coords.longitude },
      fillColor: COLORS.red, strokeColor: COLORS.red,
      strokeWeight: 1, fillOpacity: 0.3, strokeOpacity: 0.7, radius,
    }]);
  };

  const hideStationaryCircle = async () => {
    if (MARKERS.stationaryCircle) {
      await map?.removeCircles(MARKERS.stationaryCircle);
      MARKERS.stationaryCircle = null;
    }
  };

  const clearMarkers = async () => {
    if (!map) return;
    if (MARKERS.stationaryCircle) { map.removeCircles(MARKERS.stationaryCircle); MARKERS.stationaryCircle = null; }
    if (MARKERS.locationMarkers.length) { map.removeMarkers(MARKERS.locationMarkers); MARKERS.locationMarkers = []; }
    if (MARKERS.polyline) { map.removePolylines(MARKERS.polyline); MARKERS.polyline = null; POLYLINE_PATH.splice(0); }
    if (MARKERS.activeGeofences) { map.removeCircles(MARKERS.activeGeofences); MARKERS.activeGeofences = null; }
    if (MARKERS.activePolygons) { map.removePolygons(MARKERS.activePolygons); MARKERS.activePolygons = null; }
    if (MARKERS.geofenceEventMarkers.length) { map.removeMarkers(MARKERS.geofenceEventMarkers); MARKERS.geofenceEventMarkers = []; }
    if (MARKERS.geofenceEventPolylines.length) { map.removePolylines(MARKERS.geofenceEventPolylines); MARKERS.geofenceEventPolylines = []; }
    if (MARKERS.motionChangePolylines.length) { map.removePolylines(MARKERS.motionChangePolylines); MARKERS.motionChangePolylines = []; }
    if (MARKERS.motionChangeCircles.length) { map.removeCircles(MARKERS.motionChangeCircles); MARKERS.motionChangeCircles = []; }
  };

  // Geofence helpers
  const updateGeofences = async (event: GeofencesChangeEvent) => {
    if (MARKERS.activeGeofences) await map?.removeCircles(MARKERS.activeGeofences);
    if (MARKERS.activePolygons) await map?.removePolygons(MARKERS.activePolygons);

    if (event.on.length === 0 && event.off.length === 0) {
      MARKERS.activeGeofences = null;
      MARKERS.activePolygons = null;
      return;
    }

    event.off.forEach((id: string) => ACTIVE_GEOFENCES.delete(id));
    event.on.forEach((gf: Geofence) => ACTIVE_GEOFENCES.set(gf.identifier, gf));

    const circles: any[] = [];
    const polygons: any[] = [];
    ACTIVE_GEOFENCES.forEach(gf => {
      circles.push(buildGeofenceCircle(gf));
      if (gf.vertices && gf.vertices.length > 0) polygons.push(buildGeofencePolygon(gf));
    });

    if (circles.length > 0) MARKERS.activeGeofences = await map?.addCircles(circles);
    if (polygons.length > 0) MARKERS.activePolygons = await map?.addPolygons(polygons);
  };

  const buildGeofenceCircle = (gf: Geofence) => ({
    identifier: gf.identifier,
    zIndex: 1,
    fillColor: COLORS.green, fillOpacity: 0.2,
    strokeColor: COLORS.green, strokeWeight: 2, strokeOpacity: 1.0,
    params: gf,
    radius: gf.radius,
    center: { lat: gf.latitude, lng: gf.longitude },
  });

  const buildGeofencePolygon = (gf: Geofence) => ({
    zIndex: 2,
    strokeColor: COLORS.blue, strokeWeight: 5, strokeOpacity: 0.7,
    fillColor: COLORS.polygon_fill_color, fillOpacity: 0.4,
    geodesic: true, clickable: false,
    title: gf.identifier,
    paths: (gf.vertices || []).map((v: any) => ({ lat: v[0], lng: v[1] })),
  });

  const handleGeofenceEvent = async (event: GeofenceEvent) => {
    if (!map) return;
    const gf = await BackgroundGeolocation.getGeofence(event.identifier);
    const loc = event.location;

    const center = { latitude: gf.latitude, longitude: gf.longitude };

    let iconColor: string;
    if (event.action === 'ENTER') { iconColor = 'green'; }
    else if (event.action === 'DWELL') { iconColor = 'amber'; }
    else { iconColor = 'red'; }

    let iconIndex = (loc.coords.heading >= 0) ? Math.round(loc.coords.heading / 10) : 0;
    if (iconIndex > 36) iconIndex = 0;

    MARKERS.geofenceEventMarkers.push(await map.addMarker({
      zIndex: 100,
      coordinate: { lat: loc.coords.latitude, lng: loc.coords.longitude },
      iconUrl: `markers/location-arrow-${iconColor}-${iconIndex}.png`,
      iconSize: { width: 24, height: 24 },
      iconAnchor: { x: 10, y: 10 },
    }));

    const bearing = getBearing(center, loc.coords);
    const edgeCoord = computeOffsetCoordinate(center, gf.radius, bearing);
    if (!edgeCoord) return;

    MARKERS.geofenceEventMarkers.push(await map.addMarker({
      zIndex: 500,
      coordinate: { lat: edgeCoord.latitude, lng: edgeCoord.longitude },
      iconUrl: `markers/geofence-event-edge-circle-${event.action.toLowerCase()}.png`,
      iconSize: { width: 10, height: 10 },
      iconAnchor: { x: 5, y: 5 },
    }));

    MARKERS.geofenceEventPolylines = MARKERS.geofenceEventPolylines.concat(await map.addPolylines([{
      geodesic: true, zIndex: 99,
      strokeColor: COLORS.black, strokeOpacity: 1.0, strokeWeight: 2,
      path: [
        { lat: loc.coords.latitude, lng: loc.coords.longitude },
        { lat: edgeCoord.latitude, lng: edgeCoord.longitude },
      ],
    }]));
  };

  // Render
  return (
    <div id="MapView-container" style={{ position: 'relative', flex: 1, overflow: 'hidden' }}>
      {/* Polygon creation toolbar */}
      {isCreatingPolygon && (
        <div className="polygon-toolbar">
          <div className="polygon-toolbar-left">
            <IonButton size="small" fill="clear" onClick={onClickCancelPolygon}>Cancel</IonButton>
            <IonButton
              size="small"
              fill="clear"
              onClick={onClickUndoPolygon}
              disabled={createPolygonGeofenceCoordinates.length === 0}
            >
              Undo
            </IonButton>
          </div>
          <span className="polygon-toolbar-title">Click map to add points</span>
          <IonButton
            size="small"
            fill="solid"
            onClick={onClickAddPolygon}
            disabled={createPolygonGeofenceCoordinates.length < 3}
          >
            Next
          </IonButton>
        </div>
      )}

      {/* Geofence-click hint */}
      {!isCreatingPolygon && !props.hideAddGeofencePrompt && (
        <div id="geofence-prompt">Click map to add geofences</div>
      )}

      {/* Google Map element */}
      <capacitor-google-map
        ref={mapRef}
        style={{
          display: 'inline-block',
          width: `${mapWidth}px`,
          height: `${mapHeight}px`,
        } as React.CSSProperties}
      />

      {/* Add Geofence Type Sheet */}
      <AddGeofenceTypeSheet
        visible={isAddGeofenceTypeSheetVisible}
        onClose={() => setIsAddGeofenceTypeSheetVisible(false)}
        onSelect={onSelectAddGeofenceType}
      />

      {/* Add Geofence Sheet */}
      <AddGeofenceSheet
        visible={isAddGeofenceSheetVisible}
        coordinate={pendingGeofenceCoordinate}
        vertices={pendingPolygonVertices.length ? pendingPolygonVertices : undefined}
        onClose={() => {
          setIsAddGeofenceSheetVisible(false);
          setPendingGeofenceCoordinate(null);
          setPendingPolygonVertices([]);
          setCreatePolygonGeofenceCoordinates([]);
        }}
        onAdded={() => {
          setIsAddGeofenceSheetVisible(false);
          setPendingGeofenceCoordinate(null);
          setPendingPolygonVertices([]);
          setCreatePolygonGeofenceCoordinates([]);
        }}
      />
    </div>
  );
};

export default MapView;
